
FROM public.ecr.aws/lambda/python:3.12

# 의존성 파일 복사 및 설치
COPY requirements_lambda.txt ${LAMBDA_TASK_ROOT}
WORKDIR ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements_lambda.txt

# 애플리케이션 코드 복사
COPY package/ ${LAMBDA_TASK_ROOT}

# Lambda 핸들러 지정
CMD [ "lambda_function.lambda_handler" ]